### ISSUE TITLE
Create Sample GH and DYN scripts to pass NurbsSurface via Sockets

### ISSUE THREAD

**Issue by al-fisher** [BHoM/samples#23]
This will be a good one to add to the samples repo now functionality is in latest Beta v2.3.β.0

**Comment by enarhi** [comment]
I have a need for this script as it stands, I will go ahead and take a first pass at it.

**Comment by rwemay** [comment]
There's a related issue on this here: https://github.com/BHoM/Dynamo_Toolkit/pull/154
